### ISSUE TITLE
Posting of old kills

### ISSUE THREAD

**Issue by nizzan** [shibdib/Dramiel#155]
Problem: Killmail posting with redisQ seems to post old kills
Expected: I assume it should only post _new_ kills
I am using redisQ on the self-hosted version of the bot and it's posting old kills into our killfeed.
I heard that zkill is pulling in old kills and i assume that this is what I'm seeing.

![image](https://cloud.githubusercontent.com/assets/4788376/21520271/77b2aed8-ccf3-11e6-8c70-ad559cd5c937.png)

**Comment by shibdib** [comment]
Using only redis correct? Don't accidentally have both Killmail plugins
enabled?

On Dec 28, 2016 3:19 PM, "nizzan" <notifications@github.com> wrote:

Problem: Killmail posting with redisQ seems to post old kills
Expected: I assume it should only post *new* kills
I am using redisQ on the self-hosted version of the bot and it's posting
old kills into our killfeed.
I heard that zkill is pulling in old kills and i assume that this is what
I'm seeing.

[image: image]
<https://cloud.githubusercontent.com/assets/4788376/21520271/77b2aed8-ccf3-11e6-8c70-ad559cd5c937.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shibdib/Dramiel/issues/155>, or mute the thread
