### ISSUE TITLE
Price Check broken.

### ISSUE THREAD

**Issue by SoulDragon555** [shibdib/Dramiel#229]
* **Problem**: Price Check returning nothing.  Getting error in price.php
* **Expected**: Successful Price Check
* **Logs / Screenshots / Proof**: 
PHP Warning:  Illegal string offset 'typeID' in /home/dramiel/Dramiel/src/plugins/onMessage/price.php on line 116 in dramielError.log on any price check.  
:
Also not recognizing Avatar as a marketable item (in dramielError.log): 
PHP Warning:  SimpleXMLElement::__construct(): Entity: line 1: parser error : Start tag expected, '<' not found in /home/dramiel/Dramiel/src/plugins/onMessage/price.php on line 130
PHP Warning:  SimpleXMLElement::__construct(): A non-marketable type was given, or some other error occurred.  in /home/dramiel/Dramiel/src/plugins/onMessage/price.php on line 130
PHP Warning:  SimpleXMLElement::__construct(): ^ in /home/dramiel/Dramiel/src/plugins/onMessage/price.php on line 130
:
!pc plex and !pc 30day still work as there are hardcorded typeIDs in price.php

![image](https://cloud.githubusercontent.com/assets/28157350/25551227/6efe7a66-2c47-11e7-8edf-82a28cf701e8.png)

* **Version Info**: _PHP Version 7, Ubuntu 16.04 LTS, latest git pull

**Comment by nikander100** [comment]
Same issue here, can't acces the logs but heres a screenshot:

Expected result:  Price check
Actual result:  Comes up with 0.00 for all the values or nothing response at all
![screen shot 2017-05-08 at 14 42 26](https://cloud.githubusercontent.com/assets/24194228/25804625/e5249ac4-33fc-11e7-971f-22db7be20966.png)
Reproduction with "thorax" to see if the problem is consistent
Other things comming up with 0.00 aswel:
!jita Synth Blue Pill Booster
!jita Gecko
!jita Ogre II

no response at all
!jita Thrasher
!jita Dramiel
